### ISSUE TITLE
some question about server.js [29]

### ISSUE THREAD

**Issue by startprogress** [wayou/HiChat#7]
socket.on('disconnect', function() {
        users.splice(socket.userIndex, 1);
        socket.broadcast.emit('system', socket.nickname, users.length, 'logout');
    });

I think the parameter **socker.userIndex** should be   **socket.userIndex - 1**
Do u think so?

**Comment by wayou** [comment]
have u tested ?

**Comment by startprogress** [comment]
sorry, I was wrong. I checked it again. The origin code was right.

**Comment by startprogress** [comment]
And there is another question. I think we need to add an **# IF** at the following code:

   socket.on('disconnect', function() {
        if (socket.nickname != null){
            users.splice(socket.userIndex, 1);
            socket.broadcast.emit('system', socket.nickname, users.length, 'logout');
        }
    });

Then other users won't receive useless messages like "system [17:50:51]: null left"

**Comment by wayou** [comment]
ya, I think so. pr is appreciated.
